name: Validate Renovate config
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  validate:
    name: Validate Renovate config
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: "default.json"
